# .platform.app.yaml
name: app
type: python:3.9


disk: 2048

hooks:
  build: |
    pip install -r requirements.txt


relationships:
  database: "db:mysql"


web:
  commands:
    start: "uvicorn main:app --host '0.0.0.0' --port $PORT"
  locations:
    "/":
      passthru: true
      root: "public"

variables:
  env:
    DATABASE_URL: "mysql://user:password@database.internal:3306/mariadb"


dependencies:
  python:
    pip: true
    python-requests: ">=2.20.0"


